// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbyiBDzN3btrD7xsIIVbSNa1dDTxj2qx0',
    appId: '1:998420437315:web:87fa16818d62625fd2f7f6',
    messagingSenderId: '998420437315',
    projectId: 'e-commerce-app-67e39',
    authDomain: 'e-commerce-app-67e39.firebaseapp.com',
    storageBucket: 'e-commerce-app-67e39.appspot.com',
    measurementId: 'G-8Y1H11R1FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxKVQ-iG1fOLtA_6bzvAfMRJ6fq7wsR7s',
    appId: '1:998420437315:android:8a1536abd2111c17d2f7f6',
    messagingSenderId: '998420437315',
    projectId: 'e-commerce-app-67e39',
    storageBucket: 'e-commerce-app-67e39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY5WVfBiFtOhXXjml4R4Py1ldHqgR3440',
    appId: '1:998420437315:ios:40a17f6bc19dfce8d2f7f6',
    messagingSenderId: '998420437315',
    projectId: 'e-commerce-app-67e39',
    storageBucket: 'e-commerce-app-67e39.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY5WVfBiFtOhXXjml4R4Py1ldHqgR3440',
    appId: '1:998420437315:ios:8aca167ae87bcd5fd2f7f6',
    messagingSenderId: '998420437315',
    projectId: 'e-commerce-app-67e39',
    storageBucket: 'e-commerce-app-67e39.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
